Janitor Changes
SunsetStation/SunsetStation pull request #1197
Opened 2019-02-24 07:15 UTC by MemeProof

Changes area above HOP for janitor
Two janitors can spawn round start now
Janidrobe now has double the amount of wardrobe equipment

## Changelog
:cl: MemeProof
del: Removed spawn location in maint janitor room
tweak: Upped amount of goods in JaniDrobe
code: Upped amount of Janitors that can spawn round start to 2
map edit: Revamped the room above HOP to be a Janitor area
/:cl:

2019-02-25 17:05 UTC, alexkar598 requested changes
Remove step_y / step_x

2019-02-25 17:20 UTC, steamp0rt commented
I prefer the vacant room above HoP. Allows many rp scenarios.

2019-02-27 04:19 UTC, MemeProof commented
> Remove step_y / step_x

What exactly do you mean? I was looking through the map dmm and couldn't find a reference for this.

2019-02-27 04:20 UTC, MemeProof commented
> I prefer the vacant room above HoP. Allows many rp scenarios.

Dayz had mentioned making a small change to the area and adding an additional roundstart janitor (so now 2 possible round start), we can look at maybe moving it somewhere else.

2019-02-27 04:30 UTC, scrubmcnoob commented
The maint is plenty and there's already a ton of vacant areas elsewhere around the station. We do need two janitors though as a cleanly station will be a big role for the upcoming future.

2019-02-27 04:34 UTC, MemeProof commented
Should i rollback the map and just add another starting location for a second janitor in the current jani closet?

2019-02-27 04:36 UTC, scrubmcnoob commented
No, keep the closet as you have it right now. It looks good.

2019-02-27 20:43 UTC, steamp0rt commented
don't remove the dang vacant office

2019-02-27 20:53 UTC, SmokingKilz commented
> 
> 
> don't remove the dang vacant office

Vacant office is still there bro? It's right by arrivals.

2019-03-10 13:20 UTC, niceping requested changes

2019-03-10 13:20 UTC, kingoftheautism commented on _maps/map_files/NSS-Sunset/NSS-Sunset.dmm
> +	step_y = 0
step_y

2019-03-26 19:48 UTC, steamp0rt commented
@SmokingKilz I meant the vacant whatever-that-is. The vacant place-you-can-make-a-shop.

2019-07-16 22:54 UTC, SunsetStationuser commented
@MemeProof  this is failing travis

2019-07-16 23:45 UTC, MemeProof commented
Probably should just be removed, this was made for metastation and we aren't using that map anymore.

2019-12-19 07:40 UTC, closed without merging