Ports Vox to sunset --- Still working on refactoring sprites
SunsetStation/SunsetStation pull request #192
Opened 2018-09-26 06:32 UTC by SunsetStationuser

:cl: Bksparkie1 -- Code thanks to Ziiro and Paradise
add: Vox species
/:cl:

[why]: # Many people requested it was ported over.

2018-09-26 10:18 UTC, alexkar598 commented
This will be he'll to review

2018-09-26 10:18 UTC, alexkar598 commented
Hell*

2018-09-26 10:56 UTC, miniusAreas commented
next stop - corvids and IPC.

2018-09-26 11:02 UTC, Wilchenx commented
next stop - tajara

2018-09-26 20:19 UTC, ghost requested changes
I'm not even halfway through, this is NOT modularized

2018-09-26 20:19 UTC, steamp0rt commented on code/datums/emotes.dm
> +	var/message_vox = "" // Message to display if the user is a vox sunset
Comment is formatted wrong, it should be `// sunset -- Message to display if the user is a vox sunset`

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/cargo/packs.dm
> +					/obj/item/tank/internals/emergency_oxygen/vox,	// sunset vox emergency oxygen tank
`// sunset -- `

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/cargo/packs.dm
> +					/obj/item/tank/internals/emergency_oxygen/vox,	// sunset vox emergency oxygen tank
Or you could just do

```
// sunset start
/obj/item/tank/internals/emergency_oxygen/vox,
/obj/item/tank/internals/emergency_oxygen/vox,
/obj/item/tank/internals/emergency_oxygen/vox,
// sunset end
```

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/client/preferences.dm
> +			if("vox_body" in pref_species.mutant_bodyparts) //sunset vox bodyparts
Make this a hook proc. Like

```dat += sunset_preferences()```

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/client/preferences.dm
> +				if("vox_body") //sunset vox included
Hook!

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/client/preferences_savefile.dm
> +	S["feature_vox_body"]				>> features["vox_body"] //sunset vox body parts
Can be made into a hook proc.

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/client/preferences_savefile.dm
> +	WRITE_FILE(S["feature_vox_body"]				, features["vox_body"]) //sunset vox body parts
Can be made into a hook proc.

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/jobs/job_types/medical.dm
> +	backpack_contents = list(/obj/item/clothing/mask/surgical=1) //sunset vox mask
You can override this one var in `sunset/code/modules/jobs/job_types/medical.dm`

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/jobs/job_types/security.dm
>  	backpack_contents = list(/obj/item/storage/box/evidence=1,\
Can be overriden externally

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/jobs/job_types/security.dm
> +// /datum/outfit/job/detective/post_equip(mob/living/carbon/human/H, visualsOnly = FALSE) Sunset vox merge
Multiline comments!

```
/*
...
*/
```

Or simply add a check to see if a mask is already there.

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/mob/living/carbon/human/species.dm
> +	if("vox_quills" in mutant_bodyparts)
Hook proc!

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/mob/living/carbon/human/species.dm
> +				if("vox_body") //sunset vox bodyparts
Hook proc!

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/mob/living/carbon/human/update_icons.dm
> +				if(U.icon_override)//Done for vox and future species Sunset
```// sunset start```
and ```// sunset end```

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/surgery/organs/heart.dm
> +/obj/item/organ/heart/vox
`sunset/code/modules/surgery/organs/heart.dm`

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/surgery/organs/eyes.dm
> +
`sunset/code/modules/surgery/organs/eyes.dm`

2018-09-26 20:19 UTC, steamp0rt commented on code/modules/surgery/organs/liver.dm
> +/obj/item/organ/liver/vox
`sunset/ code/modules/surgery/organs/liver.dm`

2018-09-27 09:02 UTC, steamp0rt commented
tajara will be insta closed

2018-09-28 18:01 UTC, Ziiro commented on sunset/code/modules/hydroponics/beekeeping/beekeeper_suit.dm
> +	species_restricted = list("exclude","Vox Outcast")
https://github.com/OracleStation/OracleStation/pull/712

2018-09-28 18:02 UTC, Ziiro commented on sunset/code/modules/clothing/suits/cloaks.dm
> +/obj/item/clothing/suit/hooded/cloak/drake
https://github.com/OracleStation/OracleStation/pull/919

2018-09-28 18:04 UTC, Ziiro commented
also might want to check this PR for things I fixed:
https://github.com/OracleStation/OracleStation/pull/689

2018-09-29 03:51 UTC, SunsetStationuser commented on code/modules/surgery/organs/liver.dm
> +/obj/item/organ/liver/vox
already did, was having troubles, moved them only temporarily

2018-09-29 03:56 UTC, ghost requested changes
Looks mostly good to me, but I kinda rushed it because i'm tired.

DON'T FUCKING EDIT /tg/ DMIs!!!

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/client/preferences.dm
> +			dat += vox_preference_data(user)
```// sunset -- adds vox preferences```

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/client/preferences.dm
> +					process_vox(user)
```// sunset -- adds vox preferences```

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/client/preferences_savefile.dm
> +	load_character_vox(S)
```// sunset -- adds vox features```

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/client/preferences_savefile.dm
> +	load_character_vox_features()
```// sunset -- adds vox features```

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/client/preferences_savefile.dm
> +	save_character_vox(S)
```// sunset -- adds vox features```

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/mob/living/carbon/human/species.dm
> +		bodyparts_to_add -= handle_vox_bodyparts(H)
```// sunset -- adds vox stuff```

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/mob/living/carbon/human/species.dm
> +					handle_vox_bodyparts_features(H, S)
```// sunset -- adds vox stuff```

2018-09-29 03:56 UTC, steamp0rt commented on code/modules/surgery/organs/tongue.dm
> +		/datum/language/voxpidgin,//sunsetstation adds vox language to tongue
```// sunset -- adds vox language to tongue```

2018-09-29 03:56 UTC, steamp0rt commented on sunset/code/__HELPERS/mobs.dm
> +random_features()
/

2018-09-29 15:01 UTC, ghost reviewed
Test it,

2018-09-29 16:52 UTC, SunsetStationuser commented on code/modules/surgery/organs/lungs.dm
> +	var/oxy_damage_multiplier = 1
planning on making it affect humans and everything else in the future

2018-09-29 17:53 UTC, merged

2018-09-29 17:57 UTC, Ziiro commented
oh shit just like that huh