current resprites using retro style
SunsetStation/SunsetStation pull request #24
Opened 2018-09-13 03:24 UTC by Crysoskis

[Changelogs]: 
:cl: first batch of resprites 
imageadd: New sprites for all PDAs
imageadd: New sprite for the PDA painter
imageadd: New sprite for the autolathe
imageadd: New sprite for the turret control panel
imageadd: New sprites for most of telecommunications
/:cl:

[why]: # current sprites for the new retro style ready to be implemented. if style is agreed upon more will come, and revisions will be made to previous sprites if need be.

2018-09-13 03:47 UTC, Battletrap360 commented
NICE!

2018-09-13 10:17 UTC, alexkar598 requested changes
Only include sprites your changing in the sunset dmi files

2018-09-13 19:02 UTC, alexkar598 commented on sunset/code/game/machinery/_machinery.dm
> +	icon = 'sunset/icons/obj/stationobjs.dmi'
you really shouldnt be overriding /obj/machinery

2018-09-13 19:04 UTC, alexkar598 requested changes

2018-09-13 19:04 UTC, alexkar598 commented on sunset/code/game/machinery/_machinery.dm
> +	icon = 'sunset/icons/obj/stationobjs.dmi'
dont override /obj/machinery

2018-09-13 19:21 UTC, alexkar598 approved these changes

2018-09-13 19:24 UTC, alexkar598 requested changes
you need to fix tcomms icons,you are overriding the whole thing not individually

2018-09-13 20:29 UTC, alexkar598 approved these changes

2018-09-13 22:46 UTC, alexkar598 commented
travis is mean boi

2018-09-13 23:20 UTC, steamp0rt commented
gonna let icondiffbot do it's thing

2018-09-14 00:36 UTC, alexkar598 commented
icondiffbot went on vacation

2018-09-14 00:40 UTC, steamp0rt commented
Testmerged.

2018-09-14 02:01 UTC, steamp0rt commented
FINALLY, ICONDIFFBOT DID IT'S SHIT

2018-09-15 17:42 UTC, ghost approved these changes
Sprites are well received. Merging.

2018-09-15 17:42 UTC, merged