Ports Bay Messenger Bags
SunsetStation/SunsetStation pull request #3
Opened 2018-09-12 09:58 UTC by Xantholne

Ports messenger bags from bay/oracle

:cl: Xantholne
add: Ports messenger bags from Baystation
/:cl:

2018-09-12 15:59 UTC, Ziiro commented
Modularize this!
https://github.com/SunsetStation/SunsetStation/tree/master/sunset

2018-09-12 19:45 UTC, alexkar598 requested changes
Modularize the code AND icons

2018-09-12 19:45 UTC, alexkar598 commented on code/game/objects/items/storage/backpack.dm
> +
Modularize into its own file

2018-09-12 19:45 UTC, alexkar598 commented on code/game/objects/structures/crates_lockers/closets/secure/personal.dm
> +		new /obj/item/storage/backpack/messenger(src)
Mirror proc into its own file

2018-09-12 19:45 UTC, alexkar598 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/storage/backpack/messenger/com(src)
Mirror proc into its own file

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/captain.dm
> +	courierbag = /obj/item/storage/backpack/messenger/com
Modularize this into its own file

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/engineering.dm
> +	courierbag = /obj/item/storage/backpack/messenger/engi
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/captain.dm
> +	courierbag = /obj/item/storage/backpack/messenger/com
Modularize into its own file

2018-09-12 19:45 UTC, alexkar598 commented on code/_globalvars/lists/flavor_misc.dm
> +GLOBAL_LIST_INIT(backbaglist, list(DBACKPACK, DSATCHEL, DCOURIERBAG, DDUFFELBAG, GBACKPACK, GSATCHEL, GCOURIERBAG, GDUFFELBAG, LSATCHEL))
This _should_ be fine because it uses GLOB and thats a mess to undefine

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/engineering.dm
> +	courierbag = /obj/item/storage/backpack/messenger/engi
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/engineering.dm
> +	courierbag = /obj/item/storage/backpack/messenger/engi
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/job.dm
> +	var/courierbag = /obj/item/storage/backpack/messenger
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/job.dm
> +		if(GCOURIERBAG)
Mirror proc into its own file

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/medical.dm
> +	courierbag = /obj/item/storage/backpack/messenger/med
Modularize into its own file

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/medical.dm
> +	courierbag = /obj/item/storage/backpack/messenger/med
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/medical.dm
> +	courierbag = /obj/item/storage/backpack/messenger/chem
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/medical.dm
> +	courierbag = /obj/item/storage/backpack/messenger/med
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/medical.dm
> +	courierbag = /obj/item/storage/backpack/messenger/viro
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/science.dm
> +	courierbag = /obj/item/storage/backpack/messenger/tox
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/science.dm
> +	courierbag = /obj/item/storage/backpack/messenger/tox
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/science.dm
> +	courierbag = /obj/item/storage/backpack/messenger/tox
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/security.dm
> +	courierbag = /obj/item/storage/backpack/messenger/sec
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/security.dm
> +	courierbag = /obj/item/storage/backpack/messenger/sec
Same

2018-09-12 19:45 UTC, alexkar598 commented on code/modules/jobs/job_types/security.dm
> +	courierbag = /obj/item/storage/backpack/messenger/sec
Same

2018-09-12 23:39 UTC, alexkar598 commented
travis come to us

2018-09-12 23:39 UTC, alexkar598 commented
okay travis is mean

2018-09-14 19:54 UTC, alexkar598 commented
@Xantholne are you still working on this pr?

2018-09-17 02:24 UTC, closed without merging