fixed travis hopefully
SunsetStation/SunsetStation pull request #30
Opened 2018-09-13 18:30 UTC by SunsetStationuser

:cl: Changed yml to point to sunsetstation.dme and fixed the webhook
fix: Changed yml to point to sunsetstation.dme and fixed the webhook
/:cl:

[why]: # Hopefully this fixes travis

2018-09-13 18:58 UTC, alexkar598 submitted a review, later dismissed
should be fine

2018-09-13 20:15 UTC, alexkar598 requested changes

2018-09-13 20:15 UTC, alexkar598 commented on sunset/tools/merge-upstream-pull-request.sh
wait what the fuck @SunsetStationuser

2018-09-13 20:15 UTC, alexkar598 commented on sunset/tools/merge-upstream-pull-request.sh
> +   git remote add SunsetStation https://github.com/SunsetStation/SunsetStation.git
same

2018-09-13 20:55 UTC, steamp0rt commented
not it

2018-09-13 22:47 UTC, alexkar598 commented
travis mean boi

2018-09-14 02:27 UTC, steamp0rt commented
not the cause of the issues.

2018-09-26 20:01 UTC, alexkar598 commented
github wont let us delete the branch for some reason....

2018-09-26 20:01 UTC, closed without merging