MUSIC OVERHAUL + NEW THEMES!
SunsetStation/SunsetStation pull request #320
Opened 2018-10-06 03:22 UTC by yellowface7

New music! Hooray!

+New lavaland music to remind the miners that they are in literal hell.
+New spess music!!
+NEW THEMES **OH MY FUCKING GOD**

-old theme

This whole pr took me about a month and a half to do. More prs from me is on the way!

2018-10-06 03:55 UTC, ghost requested changes
Move the music files into `sunset/sound/...`

2018-10-06 03:55 UTC, steamp0rt commented on code/__DEFINES/sound.dm
> +											'sound/ambience/ambidanger.ogg', 'sound/ambience/ambidanger2.ogg', 'sound/ambience/ambimaint1.ogg', 'sound/ambience/ambilava.ogg',\
add a `// sunset -- add new ambience`

2018-10-06 03:55 UTC, steamp0rt commented on code/__DEFINES/sound.dm
> +#define SPACE list('sound/ambience/ambispace.ogg', 'sound/ambience/ambispace2.ogg', 'sound/ambience/ambispace3.ogg', 'sound/ambience/ambispace4.ogg', 'sound/ambience/ambiatmos.ogg')
add a `// sunset -- add new ambience`

2018-10-06 04:17 UTC, yellowface7 commented on code/__DEFINES/sound.dm
> +#define SPACE list('sound/ambience/ambispace.ogg', 'sound/ambience/ambispace2.ogg', 'sound/ambience/ambispace3.ogg', 'sound/ambience/ambispace4.ogg', 'sound/ambience/ambiatmos.ogg')
Hm? Is that for logging reasons?

2018-10-06 10:05 UTC, FlattestGuitar commented
None of the music has any credit to the authors attached, and it sure as heck doesn't look like you gave a damn about having permission to use it in the first place.

Also, I really don't think most of those fit, but I couldn't be bothered to listen to all of them.

2018-10-06 10:07 UTC, alexkar598 submitted a review, later dismissed
Either you forgot to upload ambiruin13 to ambiruin15 or you fucked up

Also give credits

2018-10-06 16:35 UTC, yellowface7 commented
Ah. I may have fucked up. I will be sure to give credits

2018-10-06 16:37 UTC, yellowface7 commented
Also, most of the ambiruin music were for lavalands. I wanted to remind the miners that they are in hell.

2018-10-06 17:30 UTC, yellowface7 commented
+Credits to all of the audio

-ambiruin13
-ambiruin14      } All of these were of human error. I fucked up at these ones.
-ambiruin15

Lavalands will have a different theme than the rest of the server since lavalands itself has a different theme. I added all of these songs to the lavalands to remind the miners that they are in hell and to add some more hellscape flavor to the lavalands.

2018-10-08 11:07 UTC, miniusAreas commented
@alexkar598 @steamp0rt Fix your stale reviews, for the sake of sanity, please.

2018-10-08 11:41 UTC, miniusAreas commented
Also @yellowface7, congrats on this, hope to see it merged. Good luck on the -html NTSL, and the telecoms shenanigins that require me to remap parts of the station :p

2018-10-09 19:49 UTC, ghost requested changes
Defines need to be modularized

2018-10-14 03:17 UTC, steamp0rt commented
Inactive, not modularized

2018-10-15 19:05 UTC, yellowface7 commented
UPDATE: I am currently working on modulating the stuff. I am currently running into errors.

2018-10-16 20:45 UTC, yellowface7 commented
COMMIT HIGHLIGHTS:

+Modularization.
+Title music is quieter
+Added titles to the music queue

-Obnoxiously loud music

2018-10-21 21:33 UTC, yellowface7 commented
Okay. Plans are in for the final push. It will go in effect either tonight or tomorrow so keep an eye out. I will ree if it doesn't push right.
=

2018-10-22 23:43 UTC, yellowface7 commented
Update: Github is crapping out right now. I accidentally deleted my repo on my computer and github won't let me redownload it because it's going through puberty or something. As soon as I am allowed to download it, I will and I will make those final changes.

Also, keep an eye out for my second pr, it will port the floor cluwne over to this server. I am almost done with it. I am currently working on the final seven errors which are pretty big ones. Hopefully that pr won't take nearly as long as this one to complete.

2018-10-28 23:47 UTC, yellowface7 commented
Still having issues with downloading the branch.

2018-11-21 07:10 UTC, yellowface7 commented
Finally, after all of this work, it should be ready to be rolled out. If there is anything I missed, please tell me.

2018-11-24 03:43 UTC, ghost approved these changes

2018-11-24 03:43 UTC, merged